version: "3"
services:
    web:
        image: lisiur/docker-demo:python
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "4001:80"
        networks:
            - webnet
networks:
    webnet:
